name: CI - Publish Eslint Config Base

on:
  push:
    branches:
      - master
    paths:
      - 'packages/base/**'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: NodeJs Evironment
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 16

      - name: Set package registry
        run: npm config set registry https://npm.pkg.github.com

      - name: Github package registry authentication
        run: npm set //npm.pkg.github.com/:_authToken ${{ secrets.PUBLISH_TOKEN_GRP }}

      - name: Npm registry authentication
        run: npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}

      - name: Publish Packages
        run: "cd packages/base
        | npm publish-grp
        | npm publish-npm"
