name: CI - Publish NPM Eslint Config Base

on:
  push:
    branches:
      - master
    paths:
      - 'packages/base/**'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: NodeJs Environment
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 16

      - name: Npm registry authentication
        run: npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}

      - name: Publish Packages
        run: cd packages/base && npm publish
